-- Generated by theme-switcher -- Oxocarbon (Default)
-- Do not edit manually. Edit theme-switcher.sh:generate_hyprland instead.
hl.config({
	general = {
		col = {
			active_border = "rgba(33b1ffff)",
			inactive_border = "rgba(161616ff)",
		},
	},
})
