general {
    before_sleep_cmd = hyprlock
    after_sleep_cmd = niri msg action power-on-monitors
}

listener {
    timeout = 900
    on-timeout = pidof hyprlock || hyprlock
}

listener {
    timeout = 930
    on-timeout = niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors
}
